import { Open_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { GlobalProvider } from "@/components/shared/global";

const font = Open_Sans({ subsets: ["cyrillic"] });

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <GlobalProvider>
                {children}
            </GlobalProvider>
        </html>
    )
}
