import { Open_Sans } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";

const font = Open_Sans({ subsets: ["cyrillic"] });

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Button variant={"outline"} className="absolute top-[5%] left-[5%]">
        <a href="/">На главную</a>
      </Button>
      <body className={cn(font.className, "h-screen")}>{children}</body>
    </html>
  )
}
